# Generated by Django 5.1.2 on 2024-11-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('food_type', models.CharField(choices=[('VEG', 'VEGETARIAN'), ('NON-VEG', 'NON-VEGETARIAN')], max_length=7)),
                ('catagory', models.CharField(choices=[('WL', 'WEIGHT-LOSS'), ('WG', 'WEIGHT-GAIN')], max_length=2)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('discription', models.TextField(max_length=400)),
            ],
        ),
    ]
