# Generated by Django 5.1.2 on 2024-11-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='discription',
            field=models.TextField(),
        ),
    ]
