# Generated by Django 5.1.2 on 2024-11-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodi', '0002_food_price_alter_food_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodi.food')),
            ],
        ),
    ]
