# Generated by Django 5.1.2 on 2024-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodi', '0003_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.FloatField(default=40.0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discounted_price',
            field=models.FloatField(editable=False),
        ),
    ]
